apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-backend
  labels:
    app: jwtexample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwtexample
  template:
    metadata:
      labels:
        app: jwtexample
    spec:
      containers:
      - name: backendpsql
        image: hzhang20902/portfoliofullstack:springboot
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: "1.0"
            memory: "8Gi"
        env:
        - name: DB_SERVER
          value: db
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: psql-db-url
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: psql-user-pass
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql-user-pass
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-backend
  labels:
    app: jwtexample
spec:
  type: NodePort
  selector:
    app: jwtexample
  ports: 
  - name: http
    port: 8080
    targetPort: 8080