apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pv-claim
  labels:
    app: portfolio
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-psql
  labels:
    app: portfolio
spec:
  ports:
  - port: 5432
  selector:
    app: portfolio
    tier: psql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-psql
  labels:
    app: portfolio
spec:
  selector:
    matchLabels:
      app: portfolio
      tier: psql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: portfolio
        tier: psql
    spec:
      containers:
      - image: hzhang20902/portfoliofullstack:db
        name: db
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: psql-db-url
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: psql-user-pass
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql-user-pass
              key: password
        - name: PG_DATA
          valueFrom:
            secretKeyRef:
              name: pg-data-path
              key: path
        ports:
        - containerPort: 5432
          name: psql
        resources:
          limits:
            memory: "2Gi"
            cpu: "1.0"
        volumeMounts:
        - name: db
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: psql-pv-claim